version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: shareit_gateway
    ports:
      - "8080:8080"
    depends_on:
    - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shareit_server
    ports:
      - "9090:9090"
    depends_on:
    - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres
    container_name: shareit
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
